import { NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { buildServerSummary, serializeAttempt } from "@/lib/progress/server-summary";
import type { AttemptRecord } from "@/lib/progress/types";
import { getCurrentAccount } from "@/lib/auth/session";
import { recordTutorialEvent } from "@/lib/game/tutorial-service";
export const runtime="nodejs";export const dynamic="force-dynamic";
export async function GET(){try{const account=await getCurrentAccount();if(!account?.family)return NextResponse.json({ok:false,error:"Non authentifié."},{status:401});const children=await prisma.child.findMany({where:{familyId:account.family.id},orderBy:{firstName:"asc"},include:{attempts:{orderBy:{completedAt:"desc"},include:{child:true,mission:true}}}});const summaries=Object.fromEntries(children.map(child=>{const attempts=child.attempts.map(serializeAttempt);return[child.slug,buildServerSummary(child,attempts)]}));const attempts=children.flatMap(child=>child.attempts.map(serializeAttempt)).sort((a,b)=>b.completedAt.localeCompare(a.completedAt));return NextResponse.json({ok:true,summaries,attempts})}catch(error){console.error("Lecture progression:",error);return NextResponse.json({ok:false,error:"Impossible de charger la progression Neon."},{status:500})}}
export async function POST(request:Request){try{const account=await getCurrentAccount();if(!account?.family)return NextResponse.json({ok:false,error:"Non authentifié."},{status:401});const payload=await request.json() as AttemptRecord;if(!payload.child||!payload.id||!payload.missionId)return NextResponse.json({ok:false,error:"Tentative invalide."},{status:400});const storedMissionId=payload.missionId.startsWith("nova-")?payload.missionId.slice(5):payload.missionId;const [child,mission]=await Promise.all([prisma.child.findFirst({where:{slug:payload.child,familyId:account.family.id}}),prisma.mission.findUnique({where:{id:storedMissionId}})]);if(!child||!mission)return NextResponse.json({ok:false,error:"Profil ou mission introuvable."},{status:404});const attempt=await prisma.attempt.upsert({where:{id:payload.id},update:{},create:{id:payload.id,childId:child.id,missionId:mission.id,correctAnswers:Math.max(0,payload.correctAnswers),totalQuestions:Math.max(1,payload.totalQuestions),mistakes:Math.max(0,payload.mistakes),hintsUsed:Math.max(0,payload.hintsUsed),durationSeconds:Math.max(1,payload.durationSeconds),completedAt:new Date(payload.completedAt)},include:{child:true,mission:true}});await recordTutorialEvent(child.id,"mission-completed");return NextResponse.json({ok:true,attempt:serializeAttempt(attempt)})}catch(error){console.error("Sauvegarde progression:",error);return NextResponse.json({ok:false,error:"La mission n’a pas pu être enregistrée dans Neon."},{status:500})}}
