import type { NarrativeChapter } from "@/lib/narrative/types";

export const chapter01: NarrativeChapter = {
  id: "season-01-chapter-01",
  slug: "le-signal-perdu",
  number: 1,
  title: "Le signal perdu",
  subtitle: "Quelque chose appelle depuis la forêt des Lucioles…",
  summary: "Oscar capte un message incomplet. Pour retrouver son origine, il faut réparer la boussole des savoirs, décoder une carte et franchir le pont des soustractions.",
  location: "La forêt des Lucioles",
  symbol: "✨",
  tracks: ["alyssio"],
  opening: [
    { speaker: "Narrateur", text: "Cette nuit-là, une lumière inconnue traverse le ciel de Mission Réussite." },
    { speaker: "Oscar", text: "Tu as vu ça ? Ma boussole vient de capter un signal… mais il est presque illisible.", mood: "worried" },
    { speaker: "Nova", text: "Le signal vient de la forêt des Lucioles. Pour le suivre, nous devons réactiver les trois fragments de la boussole.", mood: "determined" },
  ],
  missions: [
    {
      id: "chapter-01-mission-01",
      title: "Le premier fragment",
      activitySlug: "mystere-tresor",
      objective: "Comprendre le message caché dans une vieille carte.",
      intro: [{ speaker: "Oscar", text: "Le premier fragment est enfermé dans un récit. Lis bien : chaque détail peut devenir un indice." }],
      outro: [{ speaker: "Nova", text: "Fragment retrouvé ! La boussole reconnaît maintenant la direction du grand chêne.", mood: "happy" }],
    },
    {
      id: "chapter-01-mission-02",
      title: "Le marché des explorateurs",
      activitySlug: "marche-explorateurs",
      objective: "Résoudre le calcul qui permet d’obtenir une lanterne.",
      intro: [{ speaker: "Oscar", text: "La forêt est trop sombre. Il nous faut une lanterne, mais le marchand n’accepte que les bons calculs." }],
      outro: [{ speaker: "Oscar", text: "Parfait ! Avec cette lanterne, plus aucun sentier ne pourra se cacher." }],
    },
    {
      id: "chapter-01-mission-03",
      title: "Le pont des soustractions",
      activitySlug: "pont-soustractions",
      objective: "Réparer les trois dalles du vieux pont.",
      intro: [{ speaker: "Nova", text: "Chaque résultat correct consolidera une dalle. Avance avec méthode." }],
      outro: [{ speaker: "Nova", text: "Le pont tient bon. Le signal est beaucoup plus proche maintenant." }],
    },
    {
      id: "chapter-01-mission-04",
      title: "Le code de lumière",
      activitySlug: "calcul-eclair",
      objective: "Activer rapidement les trois runes lumineuses.",
      intro: [{ speaker: "Oscar", text: "Dernière étape ! Les runes s’éteignent vite : il faut calculer sans perdre de temps." }],
      outro: [{ speaker: "Narrateur", text: "Les trois runes s’illuminent. Au loin, une porte ancienne apparaît entre les arbres." }],
      reward: { id: "reward-signal-fragment", label: "Fragment de signal", description: "Le premier morceau du mystérieux message.", symbol: "📡", xpBonus: 30 },
    },
    {
      id: "chapter-01-mission-05",
      title: "Les traces sous les feuilles",
      activitySlug: "grande-bibliotheque-alyssio-001",
      objective: "Relier les indices du sentier pour retrouver la direction du signal.",
      intro: [{ speaker: "Oscar", text: "Regarde les détails : une trace minuscule peut nous montrer le bon chemin." }],
      outro: [{ speaker: "Nova", text: "Direction confirmée. Nous approchons du cœur de la forêt.", mood: "happy" }],
    },
    {
      id: "chapter-01-mission-06",
      title: "La dernière balise",
      activitySlug: "grande-bibliotheque-alyssio-002",
      objective: "Réussir l’épreuve finale pour stabiliser le premier signal.",
      intro: [{ speaker: "Nova", text: "Cette balise rassemble tout ce que tu viens d’utiliser. Avance avec confiance." }],
      outro: [{ speaker: "Narrateur", text: "Une ligne dorée traverse la boussole et révèle le chemin des Racines Chantantes." }],
    },
  ],
  completionDialogue: [
    { speaker: "Oscar", text: "On l’a fait ! Le signal dit : « Retrouvez la Porte des Mondes avant qu’elle ne se referme. »", mood: "happy" },
    { speaker: "Nova", text: "Ce n’est que le début. Derrière cette porte se trouve peut-être la clé de toutes les aventures." },
  ],
  reward: { id: "reward-boussole-lucioles", label: "Boussole des Lucioles", description: "Elle révèle les chemins invisibles de la Saison 1.", symbol: "🧭", xpBonus: 50 },
};
