import type { NarrativeChapter } from "@/lib/narrative/types";

export const chapter24: NarrativeChapter = {
  id: "season-01-chapter-24",
  slug: "le-temple-des-constellations",
  number: 24,
  title: 'Le Temple des Constellations',
  subtitle: 'Les étoiles ont caché un avertissement dans le ciel.',
  summary: 'La carte de Kael conduit l’expédition vers un observatoire suspendu. Pour lire l’avertissement des anciens, Alyssio doit ordonner des informations, reconnaître des régularités et interpréter un récit céleste.',
  location: 'Le Temple des Constellations',
  symbol: "🌌",
  tracks: ["alyssio"],
  opening: [
    { speaker: 'Narrateur', text: 'Une plateforme s’élève au-dessus des nuages et rejoint un temple où les murs sont ouverts sur le ciel.', mood: 'calm' },
    { speaker: 'Kael', text: 'Les mécanismes suivent les étoiles, mais certaines constellations ont été déplacées.', mood: 'worried' },
    { speaker: 'Lyra', text: 'L’Ombre veut effacer l’avertissement des anciens. Nous devons le lire avant la prochaine nuit.', mood: 'determined' },
  ],
  missions: [
    {
      id: "chapter-24-mission-01",
      title: 'L’étoile repère',
      activitySlug: "grande-bibliotheque-alyssio-135",
      objective: 'Identifier l’information explicite qui permet d’orienter la carte du ciel.',
      intro: [{ speaker: 'Lyra', text: 'Commence par l’étoile dont la position est donnée avec certitude.' }],
      outro: [{ speaker: 'Nova', text: 'Point de repère établi. Les autres constellations peuvent être replacées.', mood: "happy" }],
    },
    {
      id: "chapter-24-mission-02",
      title: 'Les orbites chiffrées',
      activitySlug: "grande-bibliotheque-alyssio-136",
      objective: 'Calculer les déplacements nécessaires pour aligner les anneaux célestes.',
      intro: [{ speaker: 'Kael', text: 'Chaque anneau avance selon un nombre précis. Écris les étapes.' }],
      outro: [{ speaker: 'Oscar', text: 'Les anneaux tournent ensemble. Le ciel se dessine au plafond.', mood: "happy" }],
    },
    {
      id: "chapter-24-mission-03",
      title: 'La légende des Veilleurs',
      activitySlug: "grande-bibliotheque-alyssio-137",
      objective: 'Comprendre l’idée principale d’un court récit ancien.',
      intro: [{ speaker: 'Oscar', text: 'Ne garde pas tous les détails. Cherche ce que les Veilleurs veulent nous transmettre.' }],
      outro: [{ speaker: 'Lyra', text: 'Le message parle d’un cœur de lumière protégé par un labyrinthe vivant.', mood: "happy" }],
    },
    {
      id: "chapter-24-mission-04",
      title: 'La suite des étoiles',
      activitySlug: "grande-bibliotheque-alyssio-138",
      objective: 'Repérer une régularité et choisir l’élément suivant.',
      intro: [{ speaker: 'Nova', text: 'Observe ce qui se répète et ce qui change à chaque étape.' }],
      outro: [{ speaker: 'Kael', text: 'Suite complétée. Une nouvelle constellation s’allume.', mood: "happy" }],
    },
    {
      id: "chapter-24-mission-05",
      title: 'Le ciel fragmenté',
      activitySlug: "grande-bibliotheque-alyssio-139",
      objective: 'Croiser texte, position et calcul pour reconstruire la carte complète.',
      intro: [{ speaker: 'Lyra', text: 'Chaque source donne une partie de la réponse. Assemble-les avec méthode.' }],
      outro: [{ speaker: 'Nova', text: 'Carte reconstituée. Le chemin du labyrinthe apparaît au nord.', mood: "happy" }],
    },
    {
      id: "chapter-24-mission-06",
      title: 'L’avertissement d’Orion',
      activitySlug: "grande-bibliotheque-alyssio-140",
      objective: 'Décoder le message final laissé par Orion, le premier Veilleur.',
      intro: [{ speaker: 'Orion', text: 'Si tu entends ma voix, c’est que l’Ombre approche du Cœur de Nova. Ne la laisse pas franchir le labyrinthe.' }],
      outro: [{ speaker: 'Narrateur', text: 'La constellation d’Orion brille puis projette une route vers une jungle mouvante.', mood: "happy" }],
    },
  ],
  completionDialogue: [
    { speaker: 'Nova', text: 'Orion connaissait mon nom… bien avant ma création. Comment est-ce possible ?', mood: 'worried' },
    { speaker: 'Oscar', text: 'Nous trouverons la réponse ensemble. Le labyrinthe nous attend.', mood: 'determined' },
  ],
  reward: {
    id: "reward-chapter-24",
    label: 'Carte des Constellations',
    description: 'Elle conserve le message d’Orion et indique les routes qui n’existent qu’à la nuit tombée.',
    symbol: "🌠",
    xpBonus: 82,
  },
};
