import type { NarrativeChapter } from "@/lib/narrative/types";

export const chapter25: NarrativeChapter = {
  id: "season-01-chapter-25",
  slug: "le-labyrinthe-vivant",
  number: 25,
  title: 'Le Labyrinthe Vivant',
  subtitle: 'Les chemins bougent à chaque hésitation.',
  summary: 'À l’entrée du labyrinthe, les murs de feuilles réagissent aux choix de l’équipe. Lyra, Kael et Oscar doivent unir leurs talents pendant qu’Alyssio construit une stratégie pour atteindre le sanctuaire central.',
  location: 'Le Labyrinthe Vivant',
  symbol: "🌿",
  tracks: ["alyssio"],
  opening: [
    { speaker: 'Narrateur', text: 'La jungle se referme derrière l’expédition. Devant elle, les haies changent de place comme si elles respiraient.', mood: 'worried' },
    { speaker: 'Kael', text: 'Impossible de fabriquer une carte fixe. Le labyrinthe apprend de nos déplacements.', mood: 'worried' },
    { speaker: 'Lyra', text: 'Alors nous ne suivrons pas un chemin : nous suivrons une méthode. Alyssio, guide-nous.', mood: 'determined' },
  ],
  missions: [
    {
      id: "chapter-25-mission-01",
      title: 'Le premier embranchement',
      activitySlug: "grande-bibliotheque-alyssio-141",
      objective: 'Repérer les indices fiables avant de choisir une direction.',
      intro: [{ speaker: 'Oscar', text: 'Ne choisis pas encore. Dis d’abord ce que chaque indice nous apprend.' }],
      outro: [{ speaker: 'Lyra', text: 'Bonne direction. Le labyrinthe accepte ton raisonnement.', mood: "happy" }],
    },
    {
      id: "chapter-25-mission-02",
      title: 'Les distances mouvantes',
      activitySlug: "grande-bibliotheque-alyssio-142",
      objective: 'Calculer et comparer plusieurs trajets possibles.',
      intro: [{ speaker: 'Kael', text: 'Le plus court trajet n’est pas toujours celui qui contient le moins d’étapes. Calcule tout.' }],
      outro: [{ speaker: 'Nova', text: 'Comparaison terminée. Le passage de l’est est le plus efficace.', mood: "happy" }],
    },
    {
      id: "chapter-25-mission-03",
      title: 'Les mots des haies',
      activitySlug: "grande-bibliotheque-alyssio-143",
      objective: 'Identifier les classes de mots qui commandent le déplacement des murs.',
      intro: [{ speaker: 'Lyra', text: 'Les verbes déclenchent une action, les noms désignent les passages. Classe-les bien.' }],
      outro: [{ speaker: 'Oscar', text: 'Les haies obéissent ! Tu viens de créer un couloir.', mood: "happy" }],
    },
    {
      id: "chapter-25-mission-04",
      title: 'La réserve des éclaireurs',
      activitySlug: "grande-bibliotheque-alyssio-144",
      objective: 'Résoudre un problème en plusieurs étapes pour répartir les provisions.',
      intro: [{ speaker: 'Kael', text: 'Note les données utiles et traite une question après l’autre.' }],
      outro: [{ speaker: 'Nova', text: 'Répartition exacte. Nous pouvons continuer sans abandonner de matériel.', mood: "happy" }],
    },
    {
      id: "chapter-25-mission-05",
      title: 'La mémoire du labyrinthe',
      activitySlug: "grande-bibliotheque-alyssio-145",
      objective: 'Relier les décisions précédentes pour anticiper le prochain déplacement.',
      intro: [{ speaker: 'Nova', text: 'Le labyrinthe répète certains comportements. Cherche la règle.' }],
      outro: [{ speaker: 'Lyra', text: 'Tu l’as anticipé. Le sanctuaire est juste derrière ce mur.', mood: "happy" }],
    },
    {
      id: "chapter-25-mission-06",
      title: 'Le sanctuaire central',
      activitySlug: "grande-bibliotheque-alyssio-146",
      objective: 'Combiner lecture, calcul et logique pour ouvrir le sanctuaire.',
      intro: [{ speaker: 'Orion', text: 'Le Cœur de Nova ne s’ouvre ni par la force ni par la vitesse, mais par un esprit capable de relier les savoirs.' }],
      outro: [{ speaker: 'Narrateur', text: 'Le sanctuaire s’ouvre. Une silhouette d’ombre s’échappe vers la Cité Perdue.', mood: "happy" }],
    },
  ],
  completionDialogue: [
    { speaker: 'Lyra', text: 'Tu nous as conduits jusqu’au centre sans jamais avancer au hasard.', mood: 'happy' },
    { speaker: 'Kael', text: 'J’ai récupéré un fragment laissé par l’Ombre. Il contient les coordonnées d’une cité disparue.', mood: 'determined' },
    { speaker: 'Nova', text: 'Et une donnée inquiétante : l’Ombre cherche mon cœur.', mood: 'worried' },
  ],
  reward: {
    id: "reward-chapter-25",
    label: 'Graine du Labyrinthe',
    description: 'Une graine magique qui mémorise les bons choix et fait pousser un chemin sûr.',
    symbol: "🌱",
    xpBonus: 88,
  },
};
