import type { NarrativeChapter } from "@/lib/narrative/types";

export const chapter21: NarrativeChapter = {
  id: "season-01-chapter-21",
  slug: "les-portes-emeraude",
  number: 21,
  title: 'Les Portes d’Émeraude',
  subtitle: 'Une cité végétale s’éveille derrière les nuages.',
  summary: 'Guidée par une nouvelle alliée, l’équipe découvre cinq portes couvertes de runes. Chacune exige observation, calcul et logique pour révéler le chemin vers le Royaume d’Émeraude.',
  location: 'Les Portes d’Émeraude',
  symbol: "💚",
  tracks: ["alyssio"],
  opening: [
    { speaker: 'Narrateur', text: 'Au-delà de la tempête, un escalier de lumière descend vers une cité entièrement recouverte de lianes.', mood: 'calm' },
    { speaker: 'Lyra', text: 'Je m’appelle Lyra, gardienne des passages. Les portes ne s’ouvrent plus depuis que l’Ombre a volé leur chant.', mood: 'worried' },
    { speaker: 'Oscar', text: 'Alors on va le retrouver. Alyssio sait déjà lire les indices que les autres ne voient pas.', mood: 'determined' },
  ],
  missions: [
    {
      id: "chapter-21-mission-01",
      title: 'La rune silencieuse',
      activitySlug: "grande-bibliotheque-alyssio-117",
      objective: 'Repérer les informations essentielles gravées sur la première porte.',
      intro: [{ speaker: 'Lyra', text: 'Les symboles parlent dans un ordre précis. Commence par ce qui est certain.' }],
      outro: [{ speaker: 'Nova', text: 'La première rune répond. Ton observation a réveillé son éclat.', mood: "happy" }],
    },
    {
      id: "chapter-21-mission-02",
      title: 'Le poids des feuilles',
      activitySlug: "grande-bibliotheque-alyssio-118",
      objective: 'Choisir le bon calcul pour équilibrer le mécanisme végétal.',
      intro: [{ speaker: 'Oscar', text: 'Chaque feuille compte. Pose ton calcul avant de toucher au mécanisme.' }],
      outro: [{ speaker: 'Lyra', text: 'L’équilibre est parfait. La deuxième porte vient de s’ouvrir.', mood: "happy" }],
    },
    {
      id: "chapter-21-mission-03",
      title: 'La phrase entrelacée',
      activitySlug: "grande-bibliotheque-alyssio-119",
      objective: 'Reconstruire le message caché dans les lianes.',
      intro: [{ speaker: 'Nova', text: 'Repère le verbe et les mots qui portent le sens de la phrase.' }],
      outro: [{ speaker: 'Oscar', text: 'Le message est complet : « Cherche la lumière sous la pierre. »', mood: "happy" }],
    },
    {
      id: "chapter-21-mission-04",
      title: 'Les cristaux jumeaux',
      activitySlug: "grande-bibliotheque-alyssio-120",
      objective: 'Résoudre une série de calculs et vérifier chaque résultat.',
      intro: [{ speaker: 'Lyra', text: 'Deux cristaux semblent identiques, mais un seul accepte un résultat vérifié.' }],
      outro: [{ speaker: 'Nova', text: 'Vérification validée. Le cristal vert indique le bon passage.', mood: "happy" }],
    },
    {
      id: "chapter-21-mission-05",
      title: 'La carte vivante',
      activitySlug: "grande-bibliotheque-alyssio-121",
      objective: 'Relier plusieurs indices pour comprendre le déplacement de la cité.',
      intro: [{ speaker: 'Oscar', text: 'La carte change quand on la regarde. Garde seulement les indices utiles.' }],
      outro: [{ speaker: 'Lyra', text: 'Tu as compris son mouvement. La cité ne pourra plus nous égarer.', mood: "happy" }],
    },
    {
      id: "chapter-21-mission-06",
      title: 'Le chant des portes',
      activitySlug: "grande-bibliotheque-alyssio-122",
      objective: 'Mobiliser les acquis du chapitre pour réactiver les cinq portes.',
      intro: [{ speaker: 'Lyra', text: 'Toutes les runes doivent maintenant vibrer ensemble. Fais confiance à ta méthode.' }],
      outro: [{ speaker: 'Narrateur', text: 'Un chant profond traverse les murailles et révèle un chemin d’émeraude.', mood: "happy" }],
    },
  ],
  completionDialogue: [
    { speaker: 'Lyra', text: 'Les portes t’ont reconnu comme un véritable explorateur des savoirs.', mood: 'happy' },
    { speaker: 'Nova', text: 'La boussole détecte un désert de cristal derrière la cité. L’Ombre y a laissé une trace récente.', mood: 'determined' },
  ],
  reward: {
    id: "reward-chapter-21",
    label: 'Clé d’Émeraude',
    description: 'Une clé vivante qui révèle les passages cachés par la végétation.',
    symbol: "🗝️",
    xpBonus: 72,
  },
};
