import type { NarrativeChapter } from "@/lib/narrative/types";

export const chapter22: NarrativeChapter = {
  id: "season-01-chapter-22",
  slug: "le-desert-cristallin",
  number: 22,
  title: 'Le Désert Cristallin',
  subtitle: 'Chaque mirage ressemble à une réponse… mais une seule est juste.',
  summary: 'Dans un désert où les dunes sont faites de verre, les mirages déforment les nombres et les phrases. Lyra apprend à l’équipe à vérifier chaque piste avant d’avancer.',
  location: 'Le Désert Cristallin',
  symbol: "💎",
  tracks: ["alyssio"],
  opening: [
    { speaker: 'Narrateur', text: 'Le chemin d’émeraude s’efface devant une étendue de cristal qui reflète mille horizons.', mood: 'calm' },
    { speaker: 'Lyra', text: 'Ici, les erreurs deviennent des mirages. Plus on se précipite, plus le désert nous éloigne.', mood: 'worried' },
    { speaker: 'Nova', text: 'Nous avancerons avec une règle simple : observer, choisir, puis vérifier.', mood: 'determined' },
  ],
  missions: [
    {
      id: "chapter-22-mission-01",
      title: 'Le reflet impossible',
      activitySlug: "grande-bibliotheque-alyssio-123",
      objective: 'Distinguer une information réelle d’un détail trompeur.',
      intro: [{ speaker: 'Oscar', text: 'Tout brille, mais tout n’est pas utile. Cherche l’indice qui ne change pas.' }],
      outro: [{ speaker: 'Lyra', text: 'Le faux horizon disparaît. Tu viens de trouver notre direction.', mood: "happy" }],
    },
    {
      id: "chapter-22-mission-02",
      title: 'Les pas de cristal',
      activitySlug: "grande-bibliotheque-alyssio-124",
      objective: 'Calculer la distance correcte entre deux balises.',
      intro: [{ speaker: 'Nova', text: 'Décompose les nombres avant de choisir le nombre de pas.' }],
      outro: [{ speaker: 'Oscar', text: 'Parfait ! Les dalles apparaissent exactement sous nos pieds.', mood: "happy" }],
    },
    {
      id: "chapter-22-mission-03",
      title: 'Le message inversé',
      activitySlug: "grande-bibliotheque-alyssio-125",
      objective: 'Identifier les mots importants dans une phrase reflétée.',
      intro: [{ speaker: 'Lyra', text: 'Lis le sens, pas seulement l’ordre des signes.' }],
      outro: [{ speaker: 'Nova', text: 'Le message retrouve sa forme véritable.', mood: "happy" }],
    },
    {
      id: "chapter-22-mission-04",
      title: 'La balance des dunes',
      activitySlug: "grande-bibliotheque-alyssio-126",
      objective: 'Résoudre un problème numérique et contrôler la cohérence du résultat.',
      intro: [{ speaker: 'Oscar', text: 'Demande-toi d’abord si la quantité doit augmenter ou diminuer.' }],
      outro: [{ speaker: 'Lyra', text: 'Le résultat est cohérent. La dune nous laisse passer.', mood: "happy" }],
    },
    {
      id: "chapter-22-mission-05",
      title: 'L’oasis cachée',
      activitySlug: "grande-bibliotheque-alyssio-127",
      objective: 'Croiser plusieurs indices pour localiser une réserve d’eau.',
      intro: [{ speaker: 'Nova', text: 'Un seul indice ne suffit pas. Relie le texte, la carte et les nombres.' }],
      outro: [{ speaker: 'Oscar', text: 'L’oasis était là ! Ton raisonnement nous a tous sauvés.', mood: "happy" }],
    },
    {
      id: "chapter-22-mission-06",
      title: 'Le prisme du nord',
      activitySlug: "grande-bibliotheque-alyssio-128",
      objective: 'Assembler les solutions du chapitre pour orienter le prisme-guide.',
      intro: [{ speaker: 'Lyra', text: 'Le prisme n’accepte que des réponses expliquées et vérifiées.' }],
      outro: [{ speaker: 'Narrateur', text: 'Un rayon vert traverse le désert et frappe une porte métallique enfouie.', mood: "happy" }],
    },
  ],
  completionDialogue: [
    { speaker: 'Oscar', text: 'Même les mirages n’ont pas réussi à te tromper !', mood: 'happy' },
    { speaker: 'Lyra', text: 'Sous le sable se trouve une ancienne fabrique. Quelqu’un l’a remise en marche.', mood: 'worried' },
  ],
  reward: {
    id: "reward-chapter-22",
    label: 'Prisme de Vérité',
    description: 'Il dissipe les illusions et fait apparaître les informations fiables.',
    symbol: "🔷",
    xpBonus: 75,
  },
};
