import type { NarrativeChapter } from "@/lib/narrative/types";

export const chapter23: NarrativeChapter = {
  id: "season-01-chapter-23",
  slug: "les-machines-oubliees",
  number: 23,
  title: 'Les Machines Oubliées',
  subtitle: 'Des engrenages anciens recommencent à tourner dans l’obscurité.',
  summary: 'L’équipe pénètre dans une fabrique abandonnée où les machines obéissent encore à des consignes incomplètes. Un jeune mécanicien nommé Kael semble connaître leur langage.',
  location: 'La Fabrique Oubliée',
  symbol: "⚙️",
  isBoss: true,
  tracks: ["alyssio"],
  opening: [
    { speaker: 'Narrateur', text: 'Sous le désert, des centaines de roues dentées se remettent soudain à tourner.', mood: 'worried' },
    { speaker: 'Kael', text: 'Ne touchez à rien ! Ces machines interprètent chaque consigne au mot près. Une erreur peut verrouiller toute la fabrique.', mood: 'determined' },
    { speaker: 'Oscar', text: 'D’accord, Kael. Alyssio sait découper un problème en étapes. On va les arrêter proprement.', mood: 'happy' },
  ],
  missions: [
    {
      id: "chapter-23-mission-01",
      title: 'La consigne incomplète',
      activitySlug: "grande-bibliotheque-alyssio-129",
      objective: 'Comprendre précisément l’action demandée par une machine.',
      intro: [{ speaker: 'Kael', text: 'Commence par le verbe de la consigne. C’est lui qui commande le mécanisme.' }],
      outro: [{ speaker: 'Nova', text: 'Instruction comprise. La première chaîne de montage ralentit.', mood: "happy" }],
    },
    {
      id: "chapter-23-mission-02",
      title: 'Les engrenages pairs',
      activitySlug: "grande-bibliotheque-alyssio-130",
      objective: 'Choisir et effectuer les calculs nécessaires pour aligner les roues.',
      intro: [{ speaker: 'Nova', text: 'Chaque engrenage doit obtenir sa valeur exacte. Vérifie avant de valider.' }],
      outro: [{ speaker: 'Kael', text: 'Alignement réussi. Tu manipules ces machines comme un vrai mécanicien.', mood: "happy" }],
    },
    {
      id: "chapter-23-mission-03",
      title: 'Le plan déchiré',
      activitySlug: "grande-bibliotheque-alyssio-131",
      objective: 'Reconstituer une phrase technique à partir de fragments.',
      intro: [{ speaker: 'Oscar', text: 'Cherche le sujet, le verbe et les compléments : le plan retrouvera son sens.' }],
      outro: [{ speaker: 'Kael', text: 'Le schéma est lisible. Nous savons maintenant quel levier actionner.', mood: "happy" }],
    },
    {
      id: "chapter-23-mission-04",
      title: 'La réserve d’énergie',
      activitySlug: "grande-bibliotheque-alyssio-132",
      objective: 'Résoudre un problème de quantité pour alimenter le bon circuit.',
      intro: [{ speaker: 'Kael', text: 'Il faut juste assez d’énergie : ni plus, ni moins. Modélise la situation.' }],
      outro: [{ speaker: 'Nova', text: 'Quantité exacte. Le circuit principal est stabilisé.', mood: "happy" }],
    },
    {
      id: "chapter-23-mission-05",
      title: 'Le défaut caché',
      activitySlug: "grande-bibliotheque-alyssio-133",
      objective: 'Relier plusieurs observations pour identifier la machine défectueuse.',
      intro: [{ speaker: 'Nova', text: 'Compare les indices au lieu de tester les machines au hasard.' }],
      outro: [{ speaker: 'Oscar', text: 'Trouvée ! Une petite roue bloquait toute la fabrique.', mood: "happy" }],
    },
    {
      id: "chapter-23-mission-06",
      title: 'Le cœur mécanique',
      activitySlug: "grande-bibliotheque-alyssio-134",
      objective: 'Appliquer toutes les stratégies du chapitre pour arrêter le cœur de la fabrique.',
      intro: [{ speaker: 'Kael', text: 'C’est le programme central. Lis chaque étape avant de commencer.' }],
      outro: [{ speaker: 'Narrateur', text: 'Les engrenages s’immobilisent. Au centre de la salle apparaît une carte céleste.', mood: "happy" }],
    },
  ],
  completionDialogue: [
    { speaker: 'Kael', text: 'Vous avez sauvé la fabrique… et vous m’avez rappelé qu’une bonne méthode vaut mieux que la vitesse.', mood: 'happy' },
    { speaker: 'Lyra', text: 'Viens avec nous, Kael. La carte indique un temple dans les étoiles.', mood: 'determined' },
  ],
  reward: {
    id: "reward-chapter-23",
    label: 'Rouage d’Inventeur',
    description: 'Un engrenage ancien qui transforme une méthode précise en énergie.',
    symbol: "⚙️",
    xpBonus: 78,
  },
};
