import { NextResponse } from "next/server";
import { getCurrentAccount } from "@/lib/auth/session";
import { prisma } from "@/lib/db/prisma";
import { ensureGameProfile, finishTutorial, recordTutorialEvent } from "@/lib/game/tutorial-service";
import { TUTORIAL_LAST_STEP, tutorialSteps, type TutorialEvent } from "@/lib/game/tutorial";
async function getOwnedChild(slug: string) { const account = await getCurrentAccount(); if (!account?.family) return null; return prisma.child.findFirst({ where: { slug, familyId: account.family.id }, include: { gameProfile: true } }); }
function payload(profile: Awaited<ReturnType<typeof ensureGameProfile>>) { return { started: profile.tutorialStarted, completed: profile.tutorialCompleted, step: profile.tutorialStep, rewardClaimed: profile.tutorialRewardClaimed, current: tutorialSteps[Math.min(profile.tutorialStep, TUTORIAL_LAST_STEP)], totalSteps: tutorialSteps.length }; }
export async function GET(request: Request) { const childSlug = new URL(request.url).searchParams.get("child"); if (!childSlug) return NextResponse.json({ error: "Profil enfant requis." }, { status: 400 }); const child = await getOwnedChild(childSlug); if (!child) return NextResponse.json({ error: "Profil introuvable." }, { status: 404 }); return NextResponse.json(payload(child.gameProfile ?? await ensureGameProfile(child.id))); }
export async function PATCH(request: Request) { const body = await request.json() as { childSlug?: string; action?: "start" | "event" | "skip-step" | "skip" | "restart" | "finish"; event?: TutorialEvent }; if (!body.childSlug || !body.action) return NextResponse.json({ error: "Action incomplète." }, { status: 400 }); const child = await getOwnedChild(body.childSlug); if (!child) return NextResponse.json({ error: "Profil introuvable." }, { status: 404 }); let profile = child.gameProfile ?? await ensureGameProfile(child.id); if (body.action === "start" || body.action === "restart") profile = await prisma.childGameProfile.update({ where: { childId: child.id }, data: { tutorialStarted: true, tutorialCompleted: false, tutorialStep: 1 } }); if (body.action === "skip") profile = await prisma.childGameProfile.update({ where: { childId: child.id }, data: { tutorialStarted: true, tutorialCompleted: true } }); if (body.action === "skip-step" && !profile.tutorialCompleted) profile = await prisma.childGameProfile.update({ where: { childId: child.id }, data: { tutorialStarted: true, tutorialStep: Math.min(TUTORIAL_LAST_STEP, profile.tutorialStep + 1), tutorialSeenHints: { push: `step-${profile.tutorialStep}-skipped` } } }); if (body.action === "event" && body.event) profile = await recordTutorialEvent(child.id, body.event); if (body.action === "finish") profile = await finishTutorial(child.id); return NextResponse.json(payload(profile)); }
